#
# Vivado (TM) v2015.2 (64-bit)
#
# MIPSfpga_project_setup.tcl: Tcl script for re-creating project 'MIPSfpga_axi4_ddr'
#
# Generated by Vivado on Fri Dec 14 10:07:48 +0800 2018
# IP Build 1264090 on Wed Jun 24 14:22:01 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************


# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

create_project MIPSfpga_axi4_ddr $origin_dir/MIPSfpga_axi4_ddr -part xc7a100tcsg324-1

import_files -norecurse $origin_dir/ram_init_os.coe
add_files -fileset constrs_1 -norecurse $origin_dir/MIPSfpga_system.xdc
import_files -fileset constrs_1 $origin_dir/MIPSfpga_system.xdc
set_property  ip_repo_paths  $origin_dir/ip_repo [current_project]
update_ip_catalog

source ./MIPSfpga_system_bd.tcl

make_wrapper -files [get_files $origin_dir/MIPSfpga_axi4_ddr/MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/MIPSfpga_system.bd] -top

add_files -norecurse $origin_dir/MIPSfpga_axi4_ddr/MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/hdl/MIPSfpga_system_wrapper.v

update_compile_order -fileset sources_1
update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
generate_target all [get_files  $origin_dir/MIPSfpga_axi4_ddr/MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/MIPSfpga_system.bd]

save_bd_design

launch_runs impl_1 -to_step write_bitstream -jobs 4

