# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/system_ability_2018/MIPSfpga_system.xdc

# Block Designs: bd/MIPSfpga_system/MIPSfpga_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system || ORIG_REF_NAME==MIPSfpga_system} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_MIPS_MicroAptiv_UP_0_0/MIPSfpga_system_MIPS_MicroAptiv_UP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_MIPS_MicroAptiv_UP_0_0 || ORIG_REF_NAME==MIPSfpga_system_MIPS_MicroAptiv_UP_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_PWM_w_Int_0_0/MIPSfpga_system_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_PWM_w_Int_0_0 || ORIG_REF_NAME==MIPSfpga_system_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_ahblite_axi_bridge_0_0/MIPSfpga_system_ahblite_axi_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_ahblite_axi_bridge_0_0 || ORIG_REF_NAME==MIPSfpga_system_ahblite_axi_bridge_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_0_0/MIPSfpga_system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_intc_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_intc_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_interconnect_0_0/MIPSfpga_system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_interconnect_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_0_0/MIPSfpga_system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_blk_mem_gen_0_0 || ORIG_REF_NAME==MIPSfpga_system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_clk_wiz_0_0 || ORIG_REF_NAME==MIPSfpga_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_mig_7series_0_0 || ORIG_REF_NAME==MIPSfpga_system_mig_7series_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/MIPSfpga_system_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_ds_buf_0_0 || ORIG_REF_NAME==MIPSfpga_system_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_0_0/MIPSfpga_system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_vector_logic_0_0 || ORIG_REF_NAME==MIPSfpga_system_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_1_0/MIPSfpga_system_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_vector_logic_1_0 || ORIG_REF_NAME==MIPSfpga_system_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_2_0/MIPSfpga_system_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_vector_logic_2_0 || ORIG_REF_NAME==MIPSfpga_system_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconcat_0_0/MIPSfpga_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconcat_0_0 || ORIG_REF_NAME==MIPSfpga_system_xlconcat_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconcat_1_0/MIPSfpga_system_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconcat_1_0 || ORIG_REF_NAME==MIPSfpga_system_xlconcat_1_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_0_0/MIPSfpga_system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_0_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_1_0/MIPSfpga_system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_1_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_1_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_2_0/MIPSfpga_system_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_2_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_2_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_3_0/MIPSfpga_system_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_3_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_3_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_4_0/MIPSfpga_system_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_4_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_4_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xbar_0/MIPSfpga_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xbar_0 || ORIG_REF_NAME==MIPSfpga_system_xbar_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0_2/MIPSfpga_system_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_1_0_1/MIPSfpga_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_WheelController_0_0_1/MIPSfpga_system_WheelController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_WheelController_0_0 || ORIG_REF_NAME==MIPSfpga_system_WheelController_0_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_6_1/MIPSfpga_system_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_6 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_6} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_5_1/MIPSfpga_system_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_5 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_5} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_5_2/MIPSfpga_system_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_5 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_5} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_4_2/MIPSfpga_system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_4 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_4} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_4/MIPSfpga_system_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_4 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_4} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_3/MIPSfpga_system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_3 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_3} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_3/MIPSfpga_system_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_3 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_3} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_2/MIPSfpga_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_2 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_2} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_cc_0/MIPSfpga_system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_cc_0 || ORIG_REF_NAME==MIPSfpga_system_auto_cc_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_2/MIPSfpga_system_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_2 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_2} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_1/MIPSfpga_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_1 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_1} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_1/MIPSfpga_system_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_1 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_1} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_0/MIPSfpga_system_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_0 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_0/MIPSfpga_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_0 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_0} -quiet] -quiet

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_us_0/MIPSfpga_system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_us_0 || ORIG_REF_NAME==MIPSfpga_system_auto_us_0} -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_ahblite_axi_bridge_0_0/MIPSfpga_system_ahblite_axi_bridge_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_0_0/MIPSfpga_system_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_intc_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_intc_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_0_0/MIPSfpga_system_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_clk_wiz_0_0 || ORIG_REF_NAME==MIPSfpga_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_clk_wiz_0_0 || ORIG_REF_NAME==MIPSfpga_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/constraints/MIPSfpga_system_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_mig_7series_0_0 || ORIG_REF_NAME==MIPSfpga_system_mig_7series_0_0} -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/constraints/MIPSfpga_system_mig_7series_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/MIPSfpga_system_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_ds_buf_0_0 || ORIG_REF_NAME==MIPSfpga_system_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/MIPSfpga_system_util_ds_buf_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_ds_buf_0_0 || ORIG_REF_NAME==MIPSfpga_system_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/MIPSfpga_system_util_ds_buf_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_xbar_0/MIPSfpga_system_xbar_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0_2/MIPSfpga_system_axi_uart16550_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0_2/MIPSfpga_system_axi_uart16550_1_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0_2/MIPSfpga_system_axi_uart16550_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_1_0_1/MIPSfpga_system_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_1_0_1/MIPSfpga_system_axi_gpio_1_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_1_0_1/MIPSfpga_system_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_6_1/MIPSfpga_system_auto_ds_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_6 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_6_1/MIPSfpga_system_auto_ds_6_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_5_1/MIPSfpga_system_auto_pc_5_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_5_2/MIPSfpga_system_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_5 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_5_2/MIPSfpga_system_auto_ds_5_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_4_2/MIPSfpga_system_auto_pc_4_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_4/MIPSfpga_system_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_4 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_4/MIPSfpga_system_auto_ds_4_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_3/MIPSfpga_system_auto_pc_3_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_3/MIPSfpga_system_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_3 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_3/MIPSfpga_system_auto_ds_3_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_2/MIPSfpga_system_auto_pc_2_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_cc_0/MIPSfpga_system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_cc_0 || ORIG_REF_NAME==MIPSfpga_system_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_cc_0/MIPSfpga_system_auto_cc_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_2/MIPSfpga_system_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_2 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_2/MIPSfpga_system_auto_ds_2_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_1/MIPSfpga_system_auto_pc_1_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_1/MIPSfpga_system_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_1 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_1/MIPSfpga_system_auto_ds_1_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_0/MIPSfpga_system_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_ds_0 || ORIG_REF_NAME==MIPSfpga_system_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_0/MIPSfpga_system_auto_ds_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_0/MIPSfpga_system_auto_pc_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_us_0/MIPSfpga_system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_us_0 || ORIG_REF_NAME==MIPSfpga_system_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_us_0/MIPSfpga_system_auto_us_0_ooc.xdc

# XDC: bd/MIPSfpga_system/MIPSfpga_system_ooc.xdc
