#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : MIPSfpga_system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Dec 09 16:38:23 +0800 2019
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: MIPSfpga_system.sh [-help]
# usage: MIPSfpga_system.sh [-lib_map_path]
# usage: MIPSfpga_system.sh [-noclean_files]
# usage: MIPSfpga_system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'MIPSfpga_system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm ahblite_axi_bridge_v3_0_13 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_14 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_19 axi_intc_v4_1_11 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_19 blk_mem_gen_v8_4_1 util_vector_logic_v2_0_1 xlconcat_v2_1_1 xlconstant_v1_1_5 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axi_protocol_converter_v2_1_17 axi_clock_converter_v2_1_16 axi_dwidth_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "MIPSfpga_system.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister_ngc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_register.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister_wide_tlb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_register_ngc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister_wide_utlb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister_wide.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_jtlb1entry.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_gf_mux2.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_and2.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_ucregister_wide.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_register_s.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_register_c.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux4.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux2.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_9.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_5.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_4.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_13.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister_s.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_cregister_c.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_utlbentry.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_jtlb4entries.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_mux2.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_bus32mux2.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_async_snd.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_async_rec.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_edp_clz_4b.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_clockxnorgate.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_8.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_6.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_latchn.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_utlb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_jtlb16entries.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mdl_add_simple.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_tck.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_tap_pcsamstub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_tap_fdcstub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_tap_dasamstub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_ibrk.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_gate.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_dbrk.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_edp_clz_16b.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_watch_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_pc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_guest_srs1.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/RAMB4_S8.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/RAMB4_S2.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/RAMB4_S16.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux8.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_3.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_24.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux1hot_10.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/mvp_mux16.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_jtlb16.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_itlb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_dtlb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_ctl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_cpy.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb_collector.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_siu_int_sync.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_rf_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_rf_rngc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mpc_exc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mpc_dec.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mpc_ctl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mmuc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mdl_dp.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mdl_ctl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_icc_umips_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_icc_spstub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_icc_spmb_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_icc_parity_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_icc_mb_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_tap.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_pdttcb_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_brk21.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt_area.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_edp_clz.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_edp_buf_misc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_edp_add_simple.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dcc_spstub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dcc_spmb_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dcc_parity_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dcc_mb_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dcc_fb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_srs1.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_sps_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_root_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_prid.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_pc_top.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_guest_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_eicoffset_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz_antitamper_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_clock_buf.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_clockandlatch.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cache_mux.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cache_cmp.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_alu_shft_32bit.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_alu_dsp_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/tagram_2k2way_xilinx.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_tlb.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_siu.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_rf_reg.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mpc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_mdl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ic_bistctl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_icc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_glue.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ejt.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_edp.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dc_bistctl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dcc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cscramble_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cscramble_scanio_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpz.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cp2_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cp1_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_clock_nogate.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cdmmstub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_biu.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/i_wsram_2k2way_xilinx.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/d_wsram_2k2way_xilinx.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/dataram_2k2way_xilinx.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ispram_ext_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_ic.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_fpuclk1_nogate.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dspram_ext_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_dc.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cscramble_tpl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_core.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cop1_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_bistctl.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_udi_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_spram_top.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cpu.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_cop2_stub.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up/m14k_top.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/mips_block_project.srcs/sources_1/new/m14k_top_wrap.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_MIPS_MicroAptiv_UP_0_0/sim/MIPSfpga_system_MIPS_MicroAptiv_UP_0_0.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/dc9a/hdl/PWM_w_Int_v1_0_S00_AXI.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/dc9a/hdl/PWM_w_Int_v1_0.v" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/dc9a/hdl/PWM_Controller_Int.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_PWM_w_Int_0_0/sim/MIPSfpga_system_PWM_w_Int_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work ahblite_axi_bridge_v3_0_13 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/df6a/hdl/ahblite_axi_bridge_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_ahblite_axi_bridge_0_0/sim/MIPSfpga_system_ahblite_axi_bridge_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_0_0/sim/MIPSfpga_system_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/sim/MIPSfpga_system_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_11 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/2fec/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/sim/MIPSfpga_system_axi_intc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uart16550_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/e469/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/sim/MIPSfpga_system_axi_uart16550_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_0_0/sim/MIPSfpga_system_blk_mem_gen_0_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_and.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_carry_or.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_1_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_clk_ibuf.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_infrastructure.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_1_tempmon.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_arb_mux.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_arb_row_col.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_arb_select.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_cntrl.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_common.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_compare.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_mach.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_queue.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_bank_state.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_col_mach.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_mc.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_rank_cntrl.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_rank_common.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_rank_mach.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_1_round_robin_arb.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_buf.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_gen.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_1_fi_xor.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_1_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_1_mem_intfc.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_calib_top.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_init.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_top.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_cc.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_edge_store.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_meta.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_pd.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_tap_base.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_1_poc_top.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_cmd.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_rd_data.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_top.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_1_ui_wr_data.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/MIPSfpga_system_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/rtl/MIPSfpga_system_mig_7series_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/sim/MIPSfpga_system_util_ds_buf_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_0_0/sim/MIPSfpga_system_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_1_0/sim/MIPSfpga_system_util_vector_logic_1_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_2_0/sim/MIPSfpga_system_util_vector_logic_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconcat_0_0/sim/MIPSfpga_system_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconcat_1_0/sim/MIPSfpga_system_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_0_0/sim/MIPSfpga_system_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_1_0/sim/MIPSfpga_system_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_2_0/sim/MIPSfpga_system_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_3_0/sim/MIPSfpga_system_xlconstant_3_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_4_0/sim/MIPSfpga_system_xlconstant_4_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_xbar_0/sim/MIPSfpga_system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/e9a5/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/2839/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/ipshared/bd6d/rtl_up" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/b65a" +incdir+"$ref_dir/../../../../MIPSfpga_axi4_ddr.srcs/sources_1/bd/MIPSfpga_system/ipshared/ec67/hdl" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_4/sim/MIPSfpga_system_auto_ds_4.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_3/sim/MIPSfpga_system_auto_pc_3.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_3/sim/MIPSfpga_system_auto_ds_3.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_2/sim/MIPSfpga_system_auto_pc_2.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_cc_0/sim/MIPSfpga_system_auto_cc_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_2/sim/MIPSfpga_system_auto_ds_2.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_1/sim/MIPSfpga_system_auto_pc_1.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_1/sim/MIPSfpga_system_auto_ds_1.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_0/sim/MIPSfpga_system_auto_ds_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_0/sim/MIPSfpga_system_auto_pc_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/ip/MIPSfpga_system_auto_us_0/sim/MIPSfpga_system_auto_us_0.v" \
    "$ref_dir/../../../bd/MIPSfpga_system/sim/MIPSfpga_system.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.MIPSfpga_system xil_defaultlib.glbl -o MIPSfpga_system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./MIPSfpga_system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./MIPSfpga_system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key MIPSfpga_system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc MIPSfpga_system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./MIPSfpga_system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: MIPSfpga_system.sh [-help]\n\
Usage: MIPSfpga_system.sh [-lib_map_path]\n\
Usage: MIPSfpga_system.sh [-reset_run]\n\
Usage: MIPSfpga_system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
