# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/mips_block_project.cache/wt [current_project]
set_property parent.project_path C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/mips_block_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged [current_project]
read_verilog {
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_const.vh
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_config.vh
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mmu.vh
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dsp_const.vh
}
read_verilog -library xil_defaultlib {
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister_ngc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_register.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister_wide_tlb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_register_ngc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister_wide_utlb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister_wide.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_jtlb1entry.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_gf_mux2.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_and2.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_ucregister_wide.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_register_s.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_register_c.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux4.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux2.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_9.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_5.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_4.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_13.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister_s.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_cregister_c.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_utlbentry.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_jtlb4entries.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_mux2.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_bus32mux2.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_async_snd.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_async_rec.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_edp_clz_4b.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_clockxnorgate.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_8.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_6.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_latchn.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_utlb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_jtlb16entries.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mdl_add_simple.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_tck.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_tap_pcsamstub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_tap_fdcstub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_tap_dasamstub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_ibrk.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_gate.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_dbrk.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_edp_clz_16b.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_watch_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_pc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_guest_srs1.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/RAMB4_S8.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/RAMB4_S2.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/RAMB4_S16.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux8.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_3.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_24.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux1hot_10.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/mvp_mux16.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_jtlb16.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_itlb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_dtlb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_ctl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_cpy.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb_collector.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_siu_int_sync.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_rf_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_rf_rngc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mpc_exc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mpc_dec.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mpc_ctl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mmuc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mdl_dp.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mdl_ctl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_icc_umips_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_icc_spstub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_icc_spmb_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_icc_parity_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_icc_mb_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_tap.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_pdttcb_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_brk21.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt_area.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_edp_clz.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_edp_buf_misc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_edp_add_simple.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dcc_spstub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dcc_spmb_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dcc_parity_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dcc_mb_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dcc_fb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_srs1.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_sps_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_root_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_prid.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_pc_top.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_guest_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_eicoffset_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz_antitamper_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_clock_buf.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_clockandlatch.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cache_mux.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cache_cmp.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_alu_shft_32bit.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_alu_dsp_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/tagram_2k2way_xilinx.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_tlb.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_siu.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_rf_reg.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mpc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_mdl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ic_bistctl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_icc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_glue.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ejt.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_edp.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dc_bistctl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dcc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cscramble_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cscramble_scanio_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpz.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cp2_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cp1_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_clock_nogate.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cdmmstub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_biu.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/i_wsram_2k2way_xilinx.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/d_wsram_2k2way_xilinx.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/dataram_2k2way_xilinx.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ispram_ext_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_ic.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_fpuclk1_nogate.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dspram_ext_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_dc.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cscramble_tpl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_core.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cop1_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_bistctl.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_udi_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_spram_top.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cpu.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_cop2_stub.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/rtl_up/m14k_top.v
  C:/workspace/MIPSfpgaSOC-Beta-2015-10/packaged_ip/my_mips_packaged/mips_block_project.srcs/sources_1/new/m14k_top_wrap.v
}
synth_design -top m14k_top_wrap -part xc7a100tcsg324-1
write_checkpoint -noxdef m14k_top_wrap.dcp
catch { report_utilization -file m14k_top_wrap_utilization_synth.rpt -pb m14k_top_wrap_utilization_synth.pb }
